### ISSUE TITLE
Make errors after latest git pull 16. feb. 2018

### ISSUE THREAD

**Issue by lb5je** [g4klx/MMDVMCal#14]
`opendv@MMDVM:~/MMDVMCal$ make
g++ -O2 -Wall -c MMDVMCal.cpp
MMDVMCal.cpp: In member function 'bool CMMDVMCal::initModem()':
MMDVMCal.cpp:260:9: error: '::memcmp' has not been declared
     if (::memcmp(m_buffer + 4U, "MMDVM ", 6U) == 0)
         ^
MMDVMCal.cpp:262:15: error: '::memcmp' has not been declared
     else if ((::memcmp(m_buffer + 4U, "ZUMspot", 7U) == 0) || (::memcmp(m_buffe
               ^
MMDVMCal.cpp:262:64: error: '::memcmp' has not been declared
     else if ((::memcmp(m_buffer + 4U, "ZUMspot", 7U) == 0) || (::memcmp(m_buffe
                                                                ^
MMDVMCal.cpp:262:119: error: '::memcmp' has not been declared
 U) == 0) || (::memcmp(m_buffer + 4U, "MMDVM_HS_Hat", 12U) == 0) || (::memcmp(m_
                                                                     ^
MMDVMCal.cpp:262:174: error: '::memcmp' has not been declared
 U) == 0) || (::memcmp(m_buffer + 4U, "Nano_hotSPOT", 12U) == 0) || (::memcmp(m_
                                                                     ^
Makefile:12: recipe for target 'MMDVMCal.o' failed
make: *** [MMDVMCal.o] Error 1
opendv@MMDVM:~/MMDVMCal$ 
`

**Comment by phl0** [comment]
Should be fixed with https://github.com/g4klx/MMDVMCal/pull/15

**Comment by lb5je** [comment]
OK now. 👍
