### ISSUE TITLE
NAK error from last MMDVM FW update

### ISSUE THREAD

**Issue by badtime** [g4klx/MMDVMCal#18]
Hi,

after the latest update in MMDVM Firmware (arduino due) MMDVMCal does not work anymore.
It show the common issue "NAK" error.
MMDVMHost work fine, i think there is a problem between new firmware and MMDVMCal.

**Comment by juribeparada** [comment]
I can't reproduce your problem. Using latest firmware for Arduino Due and latest source code of MMDVMCal, all is working good.

**Comment by badtime** [comment]
So, you have just downloaded a fresh package from git of MMDVM? Because i'm not the only user with this issue!

**Comment by juribeparada** [comment]
Are you using latest MMDVMCal from this repository too?
