### ISSUE TITLE
suggestion: add option to specify F/f step

### ISSUE THREAD

**Issue by narspt** [g4klx/MMDVMCal#23]
What do you think about adding an option (similar to E/e) to allow entering a custom step value that will then be used when changing frequency with F/f instead of the fixed 50Hz?

IMO for the new BER tests (great feature) we may want to "navigate" on smaller steps, while for eg. to check noise floor in RSSI mode it may be useful a much greater step... allowing to specify a custom step would suit all needs.

**Comment by juribeparada** [comment]
Small steps in general will not produce much improvement, after a lot of tests that I have done. Actually the PLL step is not so small (I can't remember, but could be around 25 Hz, it depends on the band). That's why 50 or 100 Hz are in general practical values for steps for most of the applications.

**Comment by narspt** [comment]
Yes, I could notice before the 25 Hz steps you mention while doing some tests in carrier mode, as sometimes it changes a bit up/down on itself with temperature changes - a good reason to want F/f working in 25 Hz steps, maybe?  But I recognize that very small step may be annoying for some other usages (like checking noise floor), that's why I suggested a custom step option to suit any possible different needs, but that is just IMO, if you don't think so then feel free to just close this issue, no problem at all.

Btw, I guess you may be reluctant to bloat the help screen with options, but you can easily put at least F/f, T/t and P/p in a single line each, then you economize at least 3 lines :-D

**Comment by juribeparada** [comment]
OK, see the last version

**Comment by narspt** [comment]
Great, thank you! Just two small details (and sorry for taking your time):
- adjusting step in 10 Hz steps doesn't allow to set it to 25 Hz step, and due to the PLL limitation you did mention, maybe just worth adjusting step in such 25 Hz steps instead? (or just allow user to directly input a fully custom step value as done in the E/e option?)
- also I think the 500 Hz up limit for step is too low, for example for noisefloor checking (as in my example above, maybe you didn't read it as I did edit my post later) I think 5000 Hz would be useful, maybe some people may want even a bit more... maybe 25000 Hz or so would be a good up limit...

**Comment by juribeparada** [comment]
Please check now, I think is more practical to enter directly the step.

**Comment by narspt** [comment]
Yes, IMO much better now. Btw think you missed a break after line 339, so it incorrectly triggers power increase also. Many thanks for your great work once again.

**Comment by phl0** [comment]
I commited a change. As I discovered that I don't have write access I put it into a PR.
@juribeparada So just a click for you :-P

**Comment by phl0** [comment]
Should be fixed in master branch. Please test again.

**Comment by juribeparada** [comment]
Thanks Flo

**Comment by narspt** [comment]
Perfect now, thanks :) I could have submitted PR myself with the fix but thought it didn't justify it :-P
