### ISSUE TITLE
100% TX/RX Levels not allowed

### ISSUE THREAD

**Issue by eb4fbz** [g4klx/MMDVMCal#4]
Hi Jonathan,

I think i've found a bug: 100% levels are not allowed like in MMDVMHost.

Value scaling is also wrong, leading to differences between cal and normal mode:
(m_rxLevel * 256U) / 100U should be (m_rxLevel * 255U) / 100U

MMDVMHost 100% = 255
MMDVMCal 100% = Not allowed
MMDVMHost 99% = 252
MMDVMCal 99% = 253
MMDVMHost 50% = 127
MMDVMCal 50% = 128

With this bug, level is slightly lower in MMDVMHost for the same rxLevel or txLevel, and a 100% value would overflow the 8bit value sent to the modem. This is specially serious at low levels because it has a big proportional impact in output deviation, but i guess no one uses low (<30%) values.

Regards,
Carlos EB4FBZ

**Comment by eb4fbz** [comment]
Hi Jonathan,

I saw you fixed the scaling, but 100% levels are still not allowed. Please fix that at lines 311 and 328. (just < 99U to < 100U).

Thanks!
Carlos EB4FBZ

**Comment by g4klx** [comment]
Done.
