### ISSUE TITLE
Full DMR testing not possible

### ISSUE THREAD

**Issue by va2na** [g4klx/MMDVMCal#6]
Hi Jonathan,

It will be very usefull to have the option to generate standard DMR partern like the 1031 to make the MMDVM full suported by DMR test gear.  The Last generation of test set will take the full picture of FSK error and BER error on the TX side using DMR test patern.  I can send you all the info .

On the RX side, the DMR test can generate RF signal with the same test patern, and we dont' have the option in MMDVMcal to display the BER result from this kind of patern.

Thank you

**Comment by g4klx** [comment]
I have no idea about what you're talking about! Do you have a reference to the technical aspects of this for me to look at?

**Comment by va2na** [comment]
Let me find you all the data and info about how we do it.

Can you give me a email adress?

Thank

Guillaume

**Comment by va2na** [comment]
Jonathan, i still not received your email adress to send you info

Guillaume

**Comment by g4klx** [comment]
I'd rather not put my email address onto a place like this. Can you send me a public message on the MMDVM Yahoo! group and I can pick up your email address from there.

**Comment by juribeparada** [comment]
MMDVMCal has 1031 test parttern now
