### ISSUE TITLE
Receiving NAK From Modem

### ISSUE THREAD

**Issue by aminhusni** [g4klx/MMDVMCal#8]
Hardware and firmware states:
Version: 1 "ZUMspot ADF7021 v1.0.2 20171023 (DStar/DMR/YSF/P25) GitID #bfb82b4"
(Same thing happens with official latest release 22e3e66)
https://github.com/juribeparada/MMDVM_HS/releases

Compiled the latest MMDVMCal d95665d  

Error message:
> Got a NAK from the modem

Replication:
`root@pi-star(rw):MMDVMCal# MMDVMCal /dev/ttyACM0`

**Comment by juribeparada** [comment]
ZUMspot (and similar hotspots) doesn't need deviation calibration, that's why you can't start MMDVMCal.

**Comment by narspt** [comment]
still it could be nice for testing... tx frequency offset, etc... ?

**Comment by juribeparada** [comment]
I'm thinking to add MMDVMCal support for testing purposes

**Comment by aminhusni** [comment]
It could be useful because all these while I had to use the Parrot to adjust certain values.

**Comment by juribeparada** [comment]
MMDVMCal support for MMDVM_HS firmware is already done
